name: Publish

on:
  release:
    types:
      - published

jobs:
  type-check:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install mypy
    - name: Run type-checking
      run: |
        mypy truncjson tests 
  test:
    needs: type-check
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install cython setuptools
        python setup.py build_ext --inplace
    - name: Run tests
      run: |
        python -m tests
  deploy:
    needs: test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: [3.5, 3.6, 3.7, 3.8, 3.9, 3.10, 3.11, 3.12]
    steps:
    - name: Check out repository
      uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install setuptools wheel twine cython cibuildwheel
    - name: Build wheel
      run: cibuildwheel --output-dir wheelhouse
      env:
        CIBW_BUILD: cp35-* cp36-* cp37-* cp38-* cp39-* cp310-* cp311-* cp312-*
    - name: Publish to PyPI
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
      run: twine upload wheelhouse/*.whl
  deploy-linux:
    needs: test
    runs-on: ubuntu-latest
    container:
      image: quay.io/pypa/manylinux2014_x86_64:latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        /opt/python/cp38-cp38/bin/pip install --upgrade pip
        /opt/python/cp38-cp38/bin/pip install setuptools wheel twine auditwheel cython
    - name: Build wheel
      run: |
        /opt/python/cp38-cp38/bin/python setup.py bdist_wheel
        /opt/python/cp38-cp38/bin/python setup.py sdist
    - name: Repair wheel
      run: |
        auditwheel repair --plat manylinux2014_x86_64 -w dist/ dist/*.whl
    - name: Publish to PyPI
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
      run: |
        /opt/python/cp38-cp38/bin/twine upload dist/*manylinux2014_x86_64.whl
        /opt/python/cp38-cp38/bin/twine upload dist/*.tar.gz
